# Wi-Fi接続情報
CIRCUITPY_WIFI_SSID="xxxxx"
CIRCUITPY_WIFI_PASSWORD="xxxxx"

# LINE Notify API から取得したTOKEN
# https://notify-bot.line.me/doc/ja/
LINE_TOKEN="xxxxx"

# Web Workflows
# https://docs.circuitpython.org/en/latest/docs/workflows.html#web
CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_API_PASSWORD="xxxxx"

# serial terminalで光センサーの値を表示しているのでこれに合わせて通知を送る閾値の値を設定する
NOTIFY_SENSOR_THRESHOLD=2